### ISSUE TITLE
Font directory SCSS variable

### ISSUE THREAD

**Issue by SimonFinney** [IBM/type#10]
Provide the ability to override default font directory in `_core.scss` to allow for specifying where fonts are located. For example:

```scss
$directory: '../fonts' !default;

@font-face {
  src: url('#{$directory}/#{$family}/web/woff2/IBMPlex#{$family}-#{$weight}-#{$unicode}.woff2') format('woff2');
}

```
